using System.Collections.Generic;
using Avalonia.Input;

namespace OpenTabletDriver.External.Avalonia.Extensions;

public static class AvaloniaKeyExtensions
{
    public static string? ConvertToEtoKeyString(this Key key)
    {
        return AvaloniaToEtoKeyMap.TryGetValue(key, out var value) ? value : null;
    }

    internal static Dictionary<Key, string> AvaloniaToEtoKeyMap { get; } = new()
    {
        { Key.None, "None" },
        { Key.A, "A" },
        { Key.B, "B" },
        { Key.C, "C" },
        { Key.D, "D" },
        { Key.E, "E" },
        { Key.F, "F" },
        { Key.G, "G" },
        { Key.H, "H" },
        { Key.I, "I" },
        { Key.J, "J" },
        { Key.K, "K" },
        { Key.L, "L" },
        { Key.M, "M" },
        { Key.N, "N" },
        { Key.O, "O" },
        { Key.P, "P" },
        { Key.Q, "Q" },
        { Key.R, "R" },
        { Key.S, "S" },
        { Key.T, "T" },
        { Key.U, "U" },
        { Key.V, "V" },
        { Key.W, "W" },
        { Key.X, "X" },
        { Key.Y, "Y" },
        { Key.Z, "Z" },
        { Key.D0, "D0" },
        { Key.D1, "D1" },
        { Key.D2, "D2" },
        { Key.D3, "D3" },
        { Key.D4, "D4" },
        { Key.D5, "D5" },
        { Key.D6, "D6" },
        { Key.D7, "D7" },
        { Key.D8, "D8" },
        { Key.D9, "D9" },
        { Key.F1, "F1" },
        { Key.F2, "F2" },
        { Key.F3, "F3" },
        { Key.F4, "F4" },
        { Key.F5, "F5" },
        { Key.F6, "F6" },
        { Key.F7, "F7" },
        { Key.F8, "F8" },
        { Key.F9, "F9" },
        { Key.F10, "F10" },
        { Key.F11, "F11" },
        { Key.F12, "F12" },
        { Key.OemMinus, "Minus" },
        { Key.OemTilde , "Grave" },
        { Key.Insert, "Insert" },
        { Key.Home, "Home" },
        { Key.PageUp, "PageUp" },
        { Key.PageDown, "PageDown" },
        { Key.Delete, "Delete" },
        { Key.End, "End" },
        { Key.Divide, "Divide" },
        { Key.Decimal, "Decimal" },
        { Key.Back, "Backspace" },
        { Key.Up, "Up" },
        { Key.Down, "Down" },
        { Key.Left, "Left" },
        { Key.Right, "Right" },
        { Key.Tab, "Tab" },
        { Key.Space, "Space" },
        { Key.CapsLock, "CapsLock" },
        { Key.Scroll, "ScrollLock" },
        { Key.PrintScreen, "PrintScreen" },
        { Key.NumLock, "NumberLock" },
        { Key.Enter, "Enter" },
        { Key.Escape, "Escape" },
        { Key.Multiply, "Multiply" },
        { Key.Add, "Add" },
        { Key.Subtract, "Subtract" },
        { Key.Help, "Help" },
        { Key.Pause, "Pause" },
        { Key.Clear, "Clear" },
        // Keypad equal
        { Key.LWin, "Menu" },
        { Key.OemBackslash, "Backslash" },
        { Key.OemPlus, "Equals" },
        { Key.OemSemicolon, "Semicolon" },
        { Key.OemQuotes, "Quote" },
        { Key.OemComma, "Comma" },
        { Key.OemPeriod, "Period" },
        { Key.Oem8, "Slash" },
        { Key.OemOpenBrackets, "LeftBracket" },
        { Key.OemCloseBrackets, "RightBracket" },
        { Key.RWin, "ContextMenu" },
        { Key.NumPad0, "KeyPad0" },
        { Key.NumPad1, "KeyPad1" },
        { Key.NumPad2, "KeyPad2" },
        { Key.NumPad3, "KeyPad3" },
        { Key.NumPad4, "KeyPad4" },
        { Key.NumPad5, "KeyPad5" },
        { Key.NumPad6, "KeyPad6" },
        { Key.NumPad7, "KeyPad7" },
        { Key.NumPad8, "KeyPad8" },
        { Key.NumPad9, "KeyPad9" },
        { Key.LeftShift, "LeftShift" },
        { Key.RightShift, "RightShift" },
        { Key.LeftCtrl, "LeftControl" },
        { Key.RightCtrl, "RightControl" },
        { Key.LeftAlt, "LeftAlt" },
        { Key.RightAlt, "RightAlt" },
        { Key.LaunchApplication1, "LeftApplication" },
        { Key.LaunchApplication2, "RightApplication" },
        // Shift
        // Alt
        // Control
        { Key.Apps, "Application"}
    };
}